name: medilink_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  uuid: ^4.5.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.0.3
  google_sign_in: ^6.2.1
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
